### PR TITLE
Add automated builds for linux, windows and mac

### PR DESCRIPTION
**Pull request by iwannet**
I added automated github actions to build for linux, windows and mac when a file gets updated.
I also added this to the readme

### CODE REVIEW

**Comment by iwannet** [comment]
but you can still use github actions right ?

**Comment by b1ek** [comment]
> but you can still use github actions right ?

yup, as long as its hosted on github. i might set up a job on [my jenkins server](https://jenkins.blek.codes) sometime later tho

**Comment by b1ek** [comment]
i have made some prebuilt binaries on the releases page for all the architectures i could think of are still used [here](https://github.com/b1ek/hey/releases/tag/0.1.1), i think that probably does what you were wanting to do

**Comment by b1ek** [comment]
merged manually in 8590387

**Pull request closed without merging**
